all:
    hosts:
        nuc:
            ansible_host: nuc-server.home
            node_type: k3s_initial_master
            ansible_user: larsv
            ansible_python_interpreter: /usr/bin/python3
